- name: Backup WordPress files
  hosts: servers
  vars:
    wp_mysql_db: mywpdb
    wp_mysql_user: myadmin
    wp_mysql_password: Admin@1234
    backup_file_name: wordpress_backup_{{ ansible_date_time.iso8601_basic_short }}.zip
    local_backup_path: "/tmp" # Replace with your actual local path
  tasks:
    - name: Ensure zip is installed
      ansible.builtin.package:
        name: zip
        state: present

    - name: Create a directory 
      ansible.builtin.file:
        path: /tmp/wordpress
        state: directory
        mode: '0755' # optional, sets the permission of the directory

    - name: Synchronize files to backup location using rsync
      ansible.builtin.command:
        cmd: rsync -av --delete /var/www/html/wordpress/ /tmp/wordpress/
      args:
        executable: /bin/bash

    - name: Backup WordPress database
      ansible.builtin.shell: mysqldump -u '{{ wp_mysql_user }}' -p'{{ wp_mysql_password }}' '{{ wp_mysql_db }}' > /tmp/wordpress/wordpress_db.sql

    - name: Zip the WordPress files and database backup
      ansible.builtin.shell: zip -r {{ backup_file_name }} /tmp/wordpress
      args:
        chdir: /tmp/wordpress/
        executable: /bin/bash

    - name: Fetch the backup zip file to the Ansible master
      ansible.builtin.fetch:
        src: "/tmp/wordpress/{{ backup_file_name }}"
        dest: "{{ local_backup_path }}/"
        flat: yes
