- hosts: local
  become: yes
  vars:
    do_api_token: dop_v1_de0b2b0143ab72e7c4a9c019ee962c1dea8c9c1bcf7c3ad421fc183b20b1be03
  gather_facts: no
    
  tasks:
    - name: Create a VPC
      community.digitalocean.digital_ocean_vpc:
        state: present
        oauth_token: "{{ do_api_token }}"
        name: VPC2
        region: ams3
        ip_range: 10.20.0.0/24
      register: my_vpc

    - name: Debug
      debug:
        msg: "VPC ID is {{ my_vpc.data.vpc.id }}"
